# Generated by Django 4.2.5 on 2023-10-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tablefile",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Description"),
        ),
    ]
