# Generated by Django 4.2.5 on 2023-10-09 16:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0002_alter_tablefile_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tablefile",
            name="file",
            field=models.FileField(
                null=True,
                upload_to="files/",
                validators=[django.core.validators.FileExtensionValidator(["csv"])],
                verbose_name="File (.csv only)",
            ),
        ),
    ]
